In [5]:
import numpy as np


# Creating arrays
a = np.array([1, 2, 3])
print("1d array:", a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print("2d array:\n", b)

zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
identity = np.eye(3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity:\n", identity)


# Array shapes and reshaping
arr = np.arange(12) # array of 0 - 11
print("Original:", arr, arr.shape)

reshaped = arr.reshape(3, 4) # reshape into 3x4
print("Reshaped:\n", reshaped)

flattened = reshaped.ravel() # flatten back
print("Flattened:", flattened)


# Elementwise operations
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print("Addition:", x + y)
print("Multiplication:", x * y)
print("Square:", x ** 2)
print("Sqrt:", np.sqrt(y))


# Indexing and slicing
m = np.array([[1, 2, 3], [4, 5, 6]])
print("First row:", m[0])
print("Second column:", m[:, 1])
print("Submatrix:\n", m[0:2, 1:3]) # rows 0-1, cols 1-2



1d array: [1 2 3]
2d array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Original: [ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Addition: [11 22 33]
Multiplication: [10 40 90]
Square: [1 4 9]
Sqrt: [3.16227766 4.47213595 5.47722558]
First row: [1 2 3]
Second column: [2 5]
Submatrix:
 [[2 3]
 [5 6]]


In [4]:
# Mini-challenges

# 1. Create 3x3 array with values 1-9. Extract:
# Second row
# Third column
# the 2x2 submatrix in the top left corner
three_x_three_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Second row:", three_x_three_array[1])
print("Third column:", three_x_three_array[:, 2])
print("Top left 2x2 submatrix:\n", three_x_three_array[0:2, 0:2])


# 2. Use np.arange() and reshape() to make a 4x4 matrix then:
# Compute the sum of each row (.sum(axis=1))
# Computer the sum of each column (.sum(axis=0))
four_x_four_matrix = np.arange(16).reshape(4, 4)
print("4x4 Matrix:\n", four_x_four_matrix)
print("Row sums:", four_x_four_matrix.sum(axis=1))
print("Column sums:", four_x_four_matrix.sum(axis=0))

Second row: [4 5 6]
Third column: [3 6 9]
Top left 2x2 submatrix:
 [[1 2]
 [4 5]]
4x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Row sums: [ 6 22 38 54]
Column sums: [24 28 32 36]
